services:
 catalogdb:
  image: postgres
 
 basketdb:
  image: postgres
 
 distributedcache:
  image: redis
 
 basket.api:
  image: ${DOCKER_REGISTRY-}basketapi
  build:
   context: .
   dockerfile: Servcies/Basket/Basket.API/Dockerfile

 catalog.api:
  image: ${DOCKER_REGISTRY-}catalogapi
  build:
   context: .
   dockerfile: Servcies/Catalog/Catalog.API/Dockerfile
   
 discount.grpc:
  image: ${DOCKER_REGISTRY-}discountgrpc
  build:
   context: .
   dockerfile: Servcies/Discount/Discount.Grpc/Dockerfile

volumes:
 postgres_catalog:
 postgres_basket:



