services:
 catalogdb:
  image: postgres

 catalog.api:
  image: ${DOCKER_REGISTRY-}catalogapi
  build:
   context: .
   dockerfile: Servcies/Catalog/Catalog.API/Dockerfile

volumes:
 postgres_catalog:

